import os
import pprint

from src.agent import ContextAgent
from src.context import Context

agent = ContextAgent(os.getenv("OPENAI_API_KEY"))
context = Context()

context.add_message("user", """
Help me write a conclusion to my paper, here are the requirements for the conclusion:
Do not repeat your abstract
o Keep it clear and concise
o Emphasise what you consider to be the significant findings or outcomes of the
investigation
o Refer back to your objectives
o Should provide technical information summary
o Should not contain any new information
o Based on your results and analysis, what can you conclude?
o You can then summarise your contributions, using a bullet point or numbered
listing
o Present future directions for your research, to address the limitations you
identified
o mention your contributions and refer back to prior studies


here is my paper:
 
 ABSTRACT: The influence of online platforms on financial markets has become increasingly apparent in the digital era, with forums like WallStreetBets playing a pivotal role in shaping asset prices and market movements. This paper aims to unravel the network structures, user interactions, and sentiment within WSB, while exploring the integration of these insights into machine learning models for predicting market phenomena. By delving into the dynamics of WSB's network and investigating the potential of incorporating network insights into stock price prediction models, this research aims to provide valuable perspectives for retail and institutional investors. The research methodology involves data collection from WSB and financial sources, sentiment analysis using the state-of-the-art sentiment models, network analysis with the Louvain algorithm, PageRank algorithm, and the evaluation of ML models including Random Forest, Feed Forward Neural Network, and Long Short-Term Memory. The results show that the inclusion of sentiment and network data enhances model performance, particularly for traditional stocks like Tesla. However, meme stocks like GameStop display distinct user behaviours and exhibit a more volatile sentiment distribution. The network analysis reveals the skewed distribution of user interactions within WSB, showcasing strong pareto principle within the network. The integration of sentiment and network insights into ML models presents opportunities for improving financial market predictions. The findings contribute to a deeper understanding of the interplay between online interactions and market dynamics, offering valuable insights for investors and future research.
 
 Introduction 
Background
The digital era has completely changed the way how information is consumed in which online platforms, particularly those centred around community discussions like Reddit, have garnered substantial influence over various domains, including financial markets. The subreddit WallStreetBets (WSB), a famous forum for retail investors to discuss investment ideas and strategies, has notably impacted the financial world, evidenced by its pivotal role in events such as the GameStop short squeeze.
Objective and Significance of the Study
This research aimed to unravel the network structures, user interactions and sentiment within WSB, thereby facilitating a comprehensive understanding of the community dynamics that underpin its influence on asset prices and market movements. Furthermore, the study aimed to incorporate insights from an in-depth network analysis and sentiment analysis to Machine Learning (ML) models, exploring the efficacy of this integration in predicting market phenomena. By delving into the intricacies of WSB's network and investigating the usage of network insights into predictive models, this research endeavours to bring valuable perspectives which could be instrumental for both retail and institutional investors, as well as related research fields.
Problem Statement
While prior studies have delved into the realm of post style, user interactions and sentiment on WSB, the nuances of its network structure and the potential of harnessing insights from such a structure for ML models remain largely unexplored. The findings from this research are intended to illuminate correlations between WSB user interactions and asset correlations, and moreover, bring insights regarding the effectiveness of leveraging such data for investment decision-making using ML models.
	Research Questions
The guiding questions for this research were:
	How is the WSB network structured, and what are the characteristics of the WSB network?
	What is the nature of the correlation between WSB user sentiment and asset movements?
	How effective is the integration of sentiment and network insights into ML models for predicting financial market movements?

The subsequent sections of this report are organised to provide a logical and coherent exposition of the research journey and findings. The Literature Review section explores existing research landscapes related to online trading communities and sentiment analysis in financial markets. The Methodology section elucidates the strategies employed for data collection, sentiment analysis, and network analysis, providing a thorough explanation of the research design and implementation. Following this, the Data Analysis section presents detailed analyses of Reddit data, network structures, and specific stock investigations. The Findings section provides a comprehensive discussion on sentiment analysis and network analysis results, as well as model evaluations. Finally, the Conclusion and Recommendations section encapsulates the key insights derived from the research, offering potential avenues for future exploration and practical applications of the findings.

Research Intent & Literature Review

Navigating through the fast-evolving landscapes of social media and financial markets, a significant amount of literature has investigated into user interactions, algorithmic influences, and collective sentiments in online platforms to tangible financial market movements. This literature review section aims to syntheses the diverse dynamics that characterize social media platforms and underlining their tremendous impact on the financial market. From exploring the underlying mechanisms and behaviours within social media spaces to analysing social media sentiment in financial arenas, this review seeks to provide a comprehensive overview, with a particular lens on studies that are relevant to understanding and leveraging the intertwining of online interactions and financial market behaviours.
Social Media Characterisation
A Vortex of User Interaction and Algorithmic Influences Exploring the labyrinth of social media platforms, the existing literature paints a vivid picture of the intricate dynamics, multifaceted user behaviours, and underlying technological mechanisms that characterize these online spaces. The spectrum of studies underlines a potent interplay between user behaviour, platform algorithms, and the overarching socio-technological environment within which they reside.
Wealth Disparities in Social Media
Guidi et al. [3] investigated into Blockchain Online Social Media (BOSM), showing a highly polarized landscape where wealth and influence are disconcertingly concentrated. The "rich gets richer" phenomenon, not only emphasises but also critically magnifies the urgent need to address the socio-economic disparities within social media platforms, particularly those which are entwined with financial mechanisms and implications. The investigation probes the problems of BOSM, highlighting the urgent and pivotal need to navigate through and potentially rectify the significant disparities within these online platforms, especially given their growing influence and impact.
Algorithmic Steering of User Engagement on Reddit
By studying Reddit’s user interactions, Glenski and Weninger [8] exposed the significant influence of algorithmic biases over user behaviours and content propagation. This study does not merely highlight algorithmic influences but also underscores the potential to harness these insights to strategically drive user engagement and content dissemination, which could be pivotal in information dissemination during critical financial events.
Unravelling Influence Cascades on Twitter
Bakshy et al. [9] investigated into Twitter’s complex influence dynamics, illustrating that while influencers play a crucial role in information cascades, pinpointing the trigger point for widespread dissemination remains elusive. This unpredictability in influence trajectories provides a nuanced perspective, advocating for a diversified and inclusive approach in leveraging online influence, especially in contexts like influencer marketing or information dissemination during market volatilities.
 Behavioural Dissection of Reddit Interactions
In a particularly relevant exploration, Thukral et al. [10] studied the user behaviours and interaction patterns on Reddit, unveiling a serious of behavioural phenomena and interaction dynamics. The researchers delved deep into the underlying behavioural patterns and dynamics that shape these interactions. They delineate the emergence of several intriguing post evolution patterns, such as the "Mayfly Buzz," which describes the majority of posts becoming inactive within a day, and "Cyborg-like behaviour," hinting at automated activity in the immediate, often elaborate comments that follow a post's publication. Moreover, the concept of "Limelight Score" is introduced to quantify the depth of discussion around a single comment, revealing that a significant portion of discussions can be cantered around one pivotal comment. Another notable introduction is the "Interaction Score," assessing author influence and showing reciprocal behaviour as a key to get attention on the platform. The findings not only cast light on the varied and multifaceted interactions on Reddit but also pave the way for potential implications in content and advertisement targeting, furnishing a crucial understanding of online social dynamics. Especially in financial contexts, where user discussions can significantly impact market dynamics, these insights are invaluable.
Social Media and the Financial Market
Navigating the complex interplay between social media sentiment and financial markets unveils a landscape where digital expressions and financial trajectories are deeply intertwined. This section synesis various studies that explored and investigated the impact of social media, particularly platforms like Reddit and Twitter, in shaping and predicting financial market movements. The objective remains to comprehend the multifaceted role of social media sentiment in financial markets, studying its predictive capabilities, and understanding its influence on decision-making processes within the financial market.
Reddit: A Melting Pot of Financial Discourse and Decision-Making
The Reddit community, particularly subreddits like r/personalfinance, as explored in a study [11], emerges as a potent space where financial discussions and behaviours are not only shaped but also tangibly measured using network analysis and topic extraction methodologies. The emotional undertones and user interactions within such platforms provide a fertile ground for understanding and potentially influencing collective financial decision-making.
Twitter's Predictive Power Over Stock Prices
Studies by Jessica and Raymond Sunardi Oetama [12, 13] illuminate Twitter’s notable potential in influencing stock price predictions, particularly when integrated with conventional financial forecasting methods. This symbiosis between social media sentiment and traditional financial analysis methodologies presents an intriguing avenue for enhancing predictive accuracy in stock price movements.
Harnessing Multi-Modal Sentiment in Financial Forecasting
Going beyond textual sentiment, a study [15] employing sentiment derived from financial video news provides a fresh perspective, suggesting that multi-modal sentiment analysis, encompassing both text and video, could offer a more comprehensive and robust mechanism for predicting financial market fluctuations.
 Integrating Sentiment and Algorithmic Predictions in Market Forecasting
Incorporating sentiment analysis with machine learning algorithms presents promising results in predicting market trends across various contexts [14, 16, 18]. These models, which incorporate sentiment data, historical stock data, and algorithmic predictions, pave the way towards creating more nuanced and accurate financial forecasting models. These studies demonstrated the enhancement sentiment data could bring into stock price and trend prediction. 

Twitter Sentiment as a Predictor for Stock Movements
An interesting venture into the realm of Twitter sentiment and its predictive power over stock market movements is undertaken by [17]. The study, “Sentiment analysis of Twitter data for predicting stock market movements,” explores the intricate relationship between the public sentiment expressed on Twitter and subsequent stock market behaviours. The authors hypothesize and demonstrate through their experiments that sentiments expressed on Twitter, both positive and negative, can be indicative of the rise and fall of stock prices, respectively.

Utilizing textual representations like Word2vec and N-gram, the authors analysed sentiments expressed in tweets related to a company, in this case, Microsoft, to explore the correlation between these sentiments and stock price movements. The authors employed sentiment analysis and supervised machine learning principles, classifying tweets into positive, negative, and neutral categories, and correlating these classifications with stock price movements. The findings of the study indicate a notable correlation between public sentiment on Twitter and stock market movements, providing a foundational basis for further exploring and validating the role of social media sentiment in predicting financial market fluctuations.

Utilizing Reddit Insights for Precise Stock Price Prediction
A highly relevant study [19] ventures into the potential of utilizing discussions from WSB to predict stock prices, concentrating on the enhancement of prediction accuracy through the using techniques of trust filter and a sliding window mechanism. The researchers not only collected sentiment of WSB posts through an individualized approach but also introduce a trust score per record and user, with the aim of identifying and harnessing reliable stock-related discussions from the seemingly chaotic expanse of user-generated content. In addition to exploring the effects of applying a sliding window approach to aggregate Reddit data, the research acknowledges the prevailing impact of sentiment within financial forums. Employing deep learning research within Natural Language Processing (NLP), it adeptly evaluates trends and establishes connections between historical sentiment and financial data. This research thereby not only assists retail investors in navigating and focusing on emerging stock opportunities by capitalizing on the collective understanding of credible advisors but also offers a method to determine the optimal window of historical social media information to be considered for adept stock analysis. 

Research Intent and Contribution
While the confluence of insights from the literature underscores the potent and pervasive influence of social media within our socio-economic contexts and the enhancement social media data could bring to the financial market prediction, certain unresolved problems and gaps in research present themselves prominently:
	Unveiling the Network Dynamics of WallStreetBets (WSB):
Though studies have begun to explore the sentiments within forums like WSB, the underlying network dynamics, including user influence, interaction patterns, and information dissemination within these platforms, remain under-explored.
	Integrating Network Dynamics into Predictive Models:
While sentiment data has been integrated into machine learning models for predicting stock prices, the incorporation of network information and influence patterns from platforms like WSB remains an avenue yet to be fully explored and understood in the context of predictive modeling.
	In-depth Characterisation of Sentiment and Influence Correlation:
Though the correlation between sentiment and stock price movements has been established, a more in-depth understanding and characterization of how network influences and sentiments within WSB correlate with financial markets are yet to be fully unraveled.
This research, therefore, steps into this pivotal gap, intending to bring to light the deeper, and perhaps, more nuanced interplays that exist within the WSB network and unravel how these insights can be harnessed to enhance machine learning model performance in predicting stock market movements. By not only integrating sentiment analysis but also characterizing and incorporating network influence from WSB, our work seeks to build upon the existing body of knowledge, offering a new lens through which the relationship between social media interactions and financial markets can be viewed and understood. Thus, the insights from this literature review not only propels our understanding forward but also forms further inquiries and explorations into this fascinating intersection where virtual and economic realms converge into tangible impacts, offering a robust foundation upon which your research can build, explore, and innovate further. Lastly, the primary goal of this research is to unearth insights from the WSB network and sentiment analysis. Firstly, this aims to offer concrete suggestions for WSB users and associated administrators. Secondly, it aims provide methods that enhance state-of-the-art machine learning models for more accurate financial market predictions, benefiting both institutional and retail traders.
Methodology 
This section explains the structured methodology used to study the relationships between social media sentiment, particularly from WSB and stock price movements, concentrating on GameStop(GME), Tesla(TSLA) and S&P 500 (SPY). It provides the details of the implementation of data collection, sentiment analysis, network analysis, and predictive modelling alongside their evaluation metrics.
Data Collection (Kevin, March - May)
 
Fig. 1. Resources used for Data Collection.

Data collection was executed using the Python Reddit API Wrapper (PRAW), Pushshift API, and The-eye Reddit archive to extract comments and posts from WSB. This resulted in approximately 3 million WSB posts. Two million comments related to TSLA and GME were extracted from The-eye Reddit archive which contains all WSB comments before 2023 March. A comment was extracted if the body of the comment contains keywords such as “TSLA”, “GME”, “Tesla” or “GameStop”. Additionally, a dataset of 100,000 comments, which represents the mainstream sentiment of WSB, was collected by extracting top-level comments from the top 100 authors. Moreover, financial data including daily price metrics for TSLA, GME, and SPY, was collected from the Yahoo Finance API. Fig. 1 provides a visualisation of the data collection and processing steps.
Data Structure (Kevin)
Attributes stored for WSB posts encompass id, title, body, upvote ratio, score, number of comments, post timestamp, and author. For comments, the stored data includes comment body, comment id, symbol, comment author, parent post, parent post author, and comment timestamp. Financial data consists of open, close, high, low, and volume daily data for TSLA, GME, and SPY stocks spanning from 2010 to 2023.
Sentiment Model and Analysis (Bill, May - September)
Both VADER and FinBERT libraries were used for this research. To determine which sentiment model works better for financial forums such as WSB, we used a financial dataset [] to compare the performance of both models. This dataset contains 10,000 data points with labelled sentiment. Our result shows an accuracy of 74% from FinBERT’s and an accuracy of 50% from VADER. Hence, we decided to use FinBERT for all future analysis. FinBERT’s categorical outputs are ("Negative", "Positive", and "Neutral"). The sentiment score for each category is -1, 1 and 0 for "Negative", "Positive", and "Neutral" respectively.  
The sentiment analysis focused on stocks including GME and TSLA. The sentiment analysis aimed to find correlations between the WSB sentiment and respective stock price movements, employing various sentiment and stock price indicators such as Daily sentiment ratio, Daily net sentiment, Exponential Moving Average (EMA), Moving Average (MA), and Stock prices percentage change. Pearson Correlation is employed to evaluate the correlation between the sentiment data and stock attributes. These indicators could potentially unveil the influence of sentiment on stock price movements.
Network Analysis (Kevin, May - August)
The network analysis is designed in a way to unveil the sophisticated structural dynamics embedded within the WSB community. We constructed a directed graph to illustrate the complex communicative pathways among the users. The following section provides the detail of the analysis we conducted on the network graph. 
Constructing the Network Graph:
A directed graph is formed by attributing an edge from the author of a comment to the original poster, representing a 'follow' or communicative relationship. Commenting and posting are the primary means of communication in WSB, hence the network graph contains majority of the user interactions information in WSB. 
Community Detection with Louvain Algorithm:
The Louvain Algorithm is employed to detect communities within the network by optimizing a modularity score, providing a quantifiable measure of community structure within the WSB network. This algorithm is widely recognised for its efficiency in detecting communities within large networks and has been utilised in various domains to identify subgroups within networks. More details for the algorithm can be found in [].
Temporal Analysis:
Temporal analysis is used to evaluate the network’s structural properties over specific time intervals, facilitates insights into dynamics such as growth, contraction, or stability within the WSB community, providing a temporal lens through which the community's evolution is observed and analysed. The metrics we used in temporal analysis including number of edges, number of nodes and average number of degrees. The number of edges and nodes represent the number of comments and users over time respectively. The average number of degrees represent the average number of interactions per user. 
Node Importance with PageRank:
The PageRank algorithm created by Google, is used to determine the relative importance of nodes within the network, identifying influential entities within the WSB community. PageRank interprets each link from one user to another as a ‘vote,’ and these votes are used to determine the importance of each user within the network, thereby illuminating influential actors within the community. More details for the algorithm can be found in []. We used the PageRank algorithm to calculate an importance score for each WSB author. This score gave insights on the influence of each author. It was used in the modelling section as a network information to enhance model performance. 
 Modelling and Evaluation (Kevin, August- October)
 
Fig. 2. Models Variations. 

We exploit various ML models, specifically Random Forest (RF), Feed Forward Neural Network (NN), and Long Short-Term Memory (LSTM) similar to [19], aiming to assess the impact of incorporating sentiment and network data into financial predictive models. Each model explores a baseline version, a sentiment-integrated model, and a weighted sentiment model. The weighted sentiment data in fig.2 is calculated by using remoralised important score then times the sentiment score, 
where WS is weighted sentiment, PRnorm is normalised PageRank score and S is sentiment,
WS(u)=PRnorm(u)×S(u)
The dataset used to train the models is from 2019-01-01 to 2023-01-01 with an 80-20 train and test split. The models’ predictive performance is evaluated against the baseline, providing evidence to the contributive value of the sentiment data. All models are evaluated using root mean square error (RMSE).
Results and Disscussions
	Sentiment and Network Insights Mostly Enhance Model Performance
Table 1: RSME of all models for predicting TSLA and GME stock price. 
	TSLA	GME
RF-FA	13.90	2.22
RF-FA-SS	13.53	2.08
RF-FA-SS-PW	13.01	2.07
FNN-FA	11.46	1.96
FNN-FA-SS	13.33	1.65
FNN-FA-SS-PW	10.41	2.37
LSTM-FA	11.28	1.98
LSTM-FA-SS	10.51	1.67
LSTM-FA-SS-PW	10.39	1.69

The outstanding pattern recognition ability from ML models led to its domination in stock price/trend prediction. It certainly is a big interest for many researchers and traders to investigate methods and techniques that can further enhance ML model performances due to the financial benefits it could potentially bring. We conducted model evaluations on RF, FNN, and LSTM. To assess the impact of sentiment data and network data on improving model performance, we started with a base model that solely utilises financial attributes (elaborated in Section 3.5). Subsequently, we integrated sentiment scores and PageRank importance scores into the model input for further evaluation. The specific configurations of these models are detailed as follows:
	RF exclusively with Financial Attributes (RF-FA)
	RF integrating Financial Attributes and Sentiment Score (RF-FA-SS)
	RF amalgamating Financial Attributes with a PageRank-weighted Sentiment Score (RF-FA-SS-PW)
	FNN focusing solely on Financial Attributes (FNN-FA)
	FNN combining Financial Attributes and Sentiment Score (FNN-FA-SS)
	FNN merging Financial Attributes with a PageRank-weighted Sentiment Score (FNN-FA-SS-PW)
	LSTM centred on Financial Attributes (LSTM-FA)
	LSTM integrating Financial Attributes and Sentiment Score (LSTM-FA-SS)
	LSTM synthesising Financial Attributes with a PageRank-weighted Sentiment Score (LSTM-FA-SS-PW)
A clear observation from our experiments was the enhancement in model performance upon the inclusion of sentiment data. This is supported by the uniform decline in RMSE values when comparing models equipped solely with Financial Attributes against those equipped with both Financial Attributes and Sentiment Scores. Such consistent improvements imply a correlation between WSB sentiment and stock price dynamics. While our sentiment analysis indicated a lagging sentiment effect in relation to stock price, it showcased minimal evidence of sentiment data leading stock price movements. This prompts us to postulate the existence of a non-linear association between sentiment data and stock price movement, a relationship potentially not captured by Pearson correlation detection.

A fascinating discovery from the model evaluation pertains to the distinct impacts of PW sentiment on TSLA and GME predictive modelling. For TSLA, the incorporation of PW persistently mitigated the RSME across all models. In stark contrast, every model for GME observed not merely an absence of performance enhancement but an actual increase in RMSE with the application of PW. This discrepancy vividly highlights the distinguished user behaviours between meme stocks and traditional stocks, inferring a notable variance in network interactions within WSB. The chaotic dynamics of meme stock networks on WSB may engender a more volatile and potentially deceptive sentiment data, introducing additional noise and thereby obstructing model generalization. Conversely, the sentiment distribution for traditional stocks like TSLA appears more stable and resilient to manipulation, rendering the insights from influential voices invaluable.

Concordantly, our results resonate with multiple studies affirming the efficacy of sentiment data in enhancing model performance [1][2][3]. While WSB sentiment may not emerge as a singular influential factor upon which retail traders should depend, its incorporation evidently bolsters the robustness of price prediction models. Our study delineates itself by unravelling the augmented utility of PW in refining sentiment data for predicting standard stock prices. Employing PW amplifies the significance of individuals possessing heightened influence and followership. In typical stock discussions, these influential individuals often demonstrate a profound comprehension of stocks and predominantly disseminate quality insights, thereby enhancing the calibre of the sentiment data. However, in the context of meme stock discussions, these influencers occasionally resort to exaggeration to instigate excitement, thereby infusing noise into the sentiment data.

D. Huynh et al. utilized trust filters on WSB data, revealing notable improvements in their findings [3]. Trust filters were employed to exclude data originating from bots and less active users by scrutinizing their posts and comments. Our methodology transcends the trust filter technique by integrating network information. Rather than discarding data, we retain all sentiment data but modulate its significance based on a network analysis of all individuals discussing a specific stock. Our outcomes indicate that utilizing PageRank scores can be particularly advantageous for conventional stocks like TSLA. The robust performance of our LSTM-FA-SS-PW model indicates its potential utility for both retail and institutional traders in enhancing predictions. Furthermore, we postulate that incorporating SS and PW into LSTM models can enhance other systems, such as those employing reinforcement learning (RL) for stock trading. For instance, numerous RL systems leverage LSTM models to predict stock prices. The addition of SS and PW to these RL systems could potentially enhance their performance.

	User Interactions Exhibit Notable Disparities between Meme and Conventional Stocks
 
Fig. 3. Normalised number of edges over time for TSLA and GME
Temporal analysis could reveal interesting insights of a network. It shows how certain metrics change overtime thereore showing the growth and progress of the network which could reveal interesting pattern of the network. Fig.3 shows a comparison between the edges of GME and TSLA network graphs overtime. The number of edges for both GME network and TSLA network are normalised to highlight the difference in its patterns. As mentioned in 3.4.1, an edge in the network graph represents a comment which is the primary method of interactions in Reddit. For stocks like GME, these graphs illuminate a significant surge in activity during events like the short squeeze, which then quickly return to pre short squeeze level. In contrast, meme stocks such as Tesla demonstrate a steadier and more consistent growth in interactions. Our data shows that meme stocks like GME, are predominantly initiated by a limited number of authors. In comparison, interactions around more conventional stocks are broader and more evenly distributed. 
There is a noticeable difference between user behaviours of meme stocks and traditional stocks in WSB, and understanding this difference can have important implications for investors. Often, individuals or groups will artificially inflate the value of these stocks in what is known as "pump and dump" tactics. They will generate hype around a stock, driving up its price, only to sell their shares once the price peaks, leaving other investors at a loss. When we see an unusually high level of activity or discussion around a particular stock, it could be a warning sign. It might indicate that the stock is being overly promoted, and there is a risk that its value could plummet soon after. This is captured by Fig.3 where the GME interactions had an unusual surge and it dropped back to normal levels soon after.  It is crucial for retail investors to be aware of these patterns and exercise caution when considering investments in such stocks. This data not only gives us a deeper understanding of the unique behaviour of meme stocks but also drives home the importance of having protective measures in place. There is a clear need for more robust regulatory frameworks to shield the market and its participants from the harmful effects of manipulative strategies.
	The WSB Community Demonstrates Pronounced Susceptibility to Manipulation through Influential Dynamics
 
Fig. 5. Comments vs authors in WSB
To verify the constant Pareto Principal findings in various studies [] and to identify dominant actors within the WSB community, network graphical analyses were employed. In this context, the Pareto Principle or the 80-20 rule, oftentimes observed within various systems, is explored alongside the PageRank algorithm to navigate through the intricate web of user interactions and influence within WSB.
Our results showed that WSB not only adhered to the Pareto Principle but exhibited an even more skewed interaction distribution, with a mere 20% of user posts captivating a staggering 97.70% of comments (Fig.5), far surpassing the conventional 80-20 distribution. This phenomenon further aligns with Zipf’s distribution (Fig.4), characterized by a slope of -1.72, signifying an extreme imbalance in the distribution of user interactions and influence. Such an extreme manifestation of the Pareto Principle in WSB implies a substantial susceptibility to market manipulation by a diminutive set of top authors wielding considerable influence over the majority of its user base.
Table 1: Top 5 PageRank results. 
Author	Score
bigbear00 OPINION_IS_UNPOPULAR	0.076
0.050
AutoModerator	0.043
Infamous_Sympathy_91	0.0035
nobjos	0.031

The execution of PageRank analysis highlighted that a subset of authors, specifically "bigbear0083" and "OPINION_IS_UNPOPULAR", exert siginificant influence within the WSB community. These highly influential figures introduce a nuanced complexity and potential for bias. The capacity for influential entities, especially moderators, to amplify or perhaps suppress particular narratives holds the potential to significantly skew the WSB network’s dialogues, thereby introducing a palpable bias that necessitates meticulous scrutiny and mitigation strategies in future community interactions and analyses.
The implementation of PageRank analysis highlighted a highly influential subset of authors within the WSB community, specifically "bigbear0083" and "OPINION_IS_UNPOPULAR" as significant human influencers and moderators. These highly influential figures introduce a nuanced complexity and potential for bias. The capacity for influential entities, especially moderators, to amplify or perhaps suppress narratives holds the potential to significantly skew the WSB network’s dialogues, thereby introducing a palpable bias that necessitates meticulous scrutiny and mitigation strategies in future community interactions and analyses.
	Revealing Influential Structures and Modularity in the WSB Network
 
Fig. 4. WSB network graph with top 100 authors
Leveraging community detection in network analysis, particularly in financial forums like WSB, provides a nuanced lens to explore and understand the intricate interplay of user interactions and collective behaviours. This approach seeks to unveil underlying structures and subgroups, revealing patterns and influential entities that may sway collective sentiments and actions within the digital ecosystem, and potentially influence market dynamics. Within the WSB ecosystem, this research studies the influence exerted by moderators and a select cohort of particularly impactful individuals. Figure 4 presents a network graph, constructed utilising comments and posts from the top 100 WSB authors. Given the constraints imposed by the graph-generating software, a sample of comments was selected from the WSB comment pool for graph generation and subsequent analysis. Comments cached from all historical posts by the top 100 top authors were chosen. Reddit’s algorithm caches prominent comments, with the number cached being contingent upon the total comment count per post and ranks them based on metrics such as upvotes and timestamps, resulting in a dataset comprising 100,000 comments. This dataset facilitated the generation of Figure 4. Furthermore, Louvain Algorithm was used for community detection (A.1), the Louvain partitions yielded a modularity score of 0.69. These communities are displayed in different colours in Figure 4.
  
Fig. 5. GME Network Graph                                       Fig.6. TSLA Network Graph
Fig.5 and Fig.6 are the network graphs for the GME and TSLA communities within WSB, respectively, formulated utilising all historical comments related to GME or TSLA in WSB (elaborated in Section 3.1). Notably, these network graphs exhibit diminished modularity compared to Figure 4, a logical occurrence considering the communities in Figure 4 predominantly pertain to distinct stock symbols. A salient observation extracted from the network graphs of GME and TSLA is the more interconnected and concentrated nature of GME in contrast to the more disseminated and relatively less connected TSLA. This reveals a propensity for the GME community to exhibit a more centralized structure than TSLA, thereby supporting the argument that meme stocks, such as GME, present an augmented susceptibility to manipulation.
	Sentiment Pattern Shows Moderate Correlation and Lagging Effect Compared to Price Movements
 
Fig.7. GME Close Price and 7-day EMA of Sentiment

Our sentiment analysis was centred on identifying potential correlations between WSB sentiment data and corresponding stock price movements, particularly given assertions from various studies regarding the enhancement of stock price predictions through sentiment data. Various sentiment and price indicators was plotted together to unveil any interesting patterns (Indicators are explained in Section 3.3). We utilised corresponding daily net sentiment data, which represents the summation of sentiment scores of comments related to a specific stock on a daily basis. This data is plot against daily stock price data. 
The correlation between GME stock price changes and net sentiment scores for related posts reports a pearson correlation of 0.40 which is the highest amongst all other indicators. During the short squeeze period (January, 2021) the sentiment and the price movement shows the highest correlation which is illustrated in Fig.7 with the overlapping pattern. Taking a closer look at the data from January 1st to March 1st of 2021, before and after the GME short squeeze event, showed  a lagging pattern in sentiment relative to stock price changes. While recognizing the inherently lagging nature of the Exponential Moving Average (EMA) indicator, even the most up-to-date net sentiment score manifested this lagging tendency. This suggests that shifts in GME’s stock price were precursors to the  sentiment alterations within WSB posts related to GME, thereby influencing community reactions based on stock performance. 
 

Fig.8. TSLA Close Price and 7-day EMA of Sentiment

A similar correlation pattern was discovered between net sentiment and TSLA stock price movements. The pinnacle of correlation was identified between the 7-day EMA of TSLA net sentiment and the subsequent day’s closing price, evidenced by a Pearson correlation of 0.29. Nevertheless, all TSLA sentiment indicators showed a lagging effect behind price changes. The study from [] also unveiled a lagging correlation between Reddit activity and stock price changes in a 1-4 day period, lack of any linear relationship between sentiment and stock price changes. The similarity of our results and the study provide more reliability in the validity of the sentiment analysis findings and implications. While the intention was to harness the results of sentiment analysis to enhance stock price prediction, our results shows the opposite relationship where is price has better predictive power. Although using WSB sentiment data for stock price prediction may not improve performance, the sentiment analysis predominantly concentrated on linear correlations. Hence, there exists a potential for the ML models to discover non-linear predictive patterns, which could enhance prediction performance.

Conclusion
 
Acknowledgements
The student would like to thank the supervisor Gerard Hanson and the sponsoring company ‘Intelligent Automation’ for providing the support and guidelines to make this project successful. Acknowledgement section has no number.


""")

res = agent.query(context)
print(res)